- azure-region/README.md
- azure-region/main.tf
Added module for azure regions
> added azure region module

- azure-region/README.md
- azure-region/main.tf
Added missing Azure regions and flags, updated errors in readme examples.
> fix: azure regions 

- new.sh
- chmod +x
- replace files in proper directory
> fix: new.sh bugs

- vscode-web/README.md
- vscode-web/main.tf
- vscode-web/run.sh
> add VS Code Web module

- .sample/README.md
chore: mention where to keep the screenshot images
> chore: mention where to keep the screenshot images

- git-commit-signing/README.md
- git-commit-signing/main.tf
- git-commit-signing/run.sh
There are no tests since it would require a valid Coder account.
https://github.com/coder/coder/issues/8922
cc: @matifali
> feat: add git-commit-signing module

- jetbrains-gateway/README.md
- jetbrains-gateway/main.test.ts
- jetbrains-gateway/main.tf
1. Updated IDEs to the latest available version
2. Remove the Community editions as they are not supported by the gateway.
> chore(jetbrans-gateway): update JetBrains IDEs

- .sample/README.md
- CONTRIBUTING.md
- README.md
- aws-region/README.md
- azure-region/README.md
- code-server/README.md
- coder-login/README.md
- dotfiles/README.md
- exoscale-instance-type/README.md
- exoscale-zone/README.md
- filebrowser/README.md
- fly-region/README.md
- gcp-region/README.md
- git-clone/README.md
- git-commit-signing/README.md
- git-config/README.md
- jetbrains-gateway/README.md
- jfrog-oauth/README.md
- jfrog-token/README.md
- jupyter-notebook/README.md
- jupyterlab/README.md
- personalize/README.md
- slackme/README.md
- vault-github/README.md
- vscode-desktop/README.md
- vscode-web/README.md
depends on https://github.com/coder/registry.coder.com/pull/11
closes #70
> feat: add version to module docs

- code-server/README.md
This PR fixes the module name in the code-server documentation
> Fix code-server docu

- jetbrains-gateway/main.tf
> Add build numbers and versions to jetbrains gateway module

- .github/workflows/update-readme.yaml
resolves https://github.com/coder/modules/actions/runs/7893919973
> ci: set base branch for docs update PR

- jetbrains-gateway/main.tf
> feat(jetbrain-gateway): add coder_pameter order

- .vscode/settings.json
- jetbrains-gateway/main.tf
> feat(jetbrains-gateway): bump version to 2024.1

- dotfiles/README.md
- dotfiles/main.tf
The output is a direct use of the input, so it is not useful.
> fix(dotfiles): fix typo and remove a less useful output

- jetbrains-gateway/main.tf
> fix(jetbrains-gateway): fix icon and name of `coder_app`

- vault-jwt/README.md
- vault-jwt/run.sh
I noticed a bug while testing this module, which was preventing to install of vault CLI.
> fix(vault-jwt): fix vault CLI installation

- jetbrains-gateway/README.md
resolves https://github.com/coder/coder/discussions/16321
> docs: add jetbrains min requirements note and link

- vscode-web/README.md
- vscode-web/main.tf
- vscode-web/run.sh
Reverts coder/modules#402
We are redoing it with suggested changes.
> Revert "feat(vscode-web): allow pinning vscode-web binary to a specific commit ID"

- goose/README.md
> chore(goose): update module version to 1.1.0

- jetbrains-gateway/README.md
This resolves a conflict with an existing tag and also resolves the required minor version bump from  #452
> chore: bump minor version number of jetbrains-gateway
