.sample/README.md
.sample/main.tf
.sample/run.sh
CONTRIBUTING.md
README.md
new.sh

@kylecarbs I merged the #31 to this PR so it will resolve both #28 and #29

add a template module and boilerplate

---

.icons/filebrowser.svg
filebrowser/README.md
filebrowser/main.tf
filebrowser/run.sh
new.sh

add filebrowser

---

code-server/main.tf

Currently the display name for the `code-server` application is just `code-server`, which personally I want to change to `VS Code`. This PR adds the option to set a custom display-name

Make `code-server` display name variable

---

aws-region/main.test.ts
aws-region/main.tf
azure-region/main.test.ts
azure-region/main.tf
jetbrains-gateway/README.md
jetbrains-gateway/main.test.ts
jetbrains-gateway/main.tf

From #66, also added testing for `jetbrains-gateway`.
Azure and AWS were simple, but there is no error message when no region is selected:
https://github.com/coder/modules/assets/58410745/9a9e317b-7764-427f-b298-86313de5fb33
Open to feedback on this.
The Jetbrains gateway default IDE satisfies a ton of logic in the template, so allowing `null` would lead to a lot of patchwork `try` statements. Now it's implemented to use the first IDE in the `jetbrains_ides` as the coder_parameter default for cleanliness. 
Let me know your thoughts.

chore: allowed empty default for modules

---

git-clone/run.sh

Hi,
fixes #79 
I hope this is ok. It's tested and works in my k8s setup (the shell script that is).
Please note, `git clone` also checks for an empty folder and not if the folder exists. So, the logic is now the same to match git clone's. :)
Scott

fix(git-clone): change to work with volumes fixes #79

---

code-server/main.test.ts
coder-login/main.tf
dotfiles/main.test.ts
fly-region/main.test.ts
gcp-region/README.md
gcp-region/main.test.ts
gcp-region/main.tf
jetbrains-gateway/main.test.ts
jupyterlab/main.test.ts
personalize/main.test.ts
test.ts
vscode-desktop/main.test.ts
vscode-desktop/main.tf
vscode-web/main.test.ts

Many modules that only required simple test cases did not leverage the testing framework added by @kylecarbs. I added most of the missing tests, though some will require either a `coder_script` shell refactor like mentioned [here](https://github.com/coder/coder/issues/9769) or conversion to Bourne shell in their respective `run.sh` files. 
Another solution to the blocked tests may be using Dockerfiles with bun to test with required packages like coder and pip. 
Related to #65.
- aws-region
- azure-region
- dotfiles
- filebrowser
- fly-region
- gcp-region
- git-clone
- git-config
- jetbrains-gateway
- jfrog
- vscode-web
- vscode-desktop
- code-server
- personalize
- coder-login (needs coder)
- jupyterlab (needs pip3)
- jupyter-notebook (needs pip3)

add missing tests

---

code-server/README.md
code-server/main.tf
code-server/run.sh

The `code-server` module advertises the ability to add any number of extensions as a list of strings. There was an error in its implementation causing the script to fail when multiple extensions were specified (pointed out by #89). 
This fixes that issue by reading the comma-separated extension list into an array.

code-server: fix multiple-extension installation

---

git-clone/main.tf

`coder_script` was introduced in [`v0.12.0`](https://registry.terraform.io/providers/coder/coder/0.12.0/docs/resources/script) and does not work on versions below this.

fix(git-clone): update the required provider version

---

jetbrains-gateway/README.md
jetbrains-gateway/main.test.ts
jetbrains-gateway/main.tf

Reverts coder/modules#96
Breaks dev.coder.com like 
```
Error: Error in function call
on .terraform/modules/jetbrains_gateway/main.tf line 129, in resource "coder_app" "gateway":
129:   display_name = data.coder_parameter.jetbrains_ide.option[index(data.coder_parameter.jetbrains_ide.option.*.value, data.coder_parameter.jetbrains_ide.value)].name
├────────────────
│ data.coder_parameter.jetbrains_ide.option is list of object with 2 elements
│ data.coder_parameter.jetbrains_ide.value is "[\"GO\",\"232.9921.53\",\"https://download.jetbrains.com/go/goland-2023.2.2.tar.gz\"]"
Call to function "index" failed: item not found.
```

Revert "chore(jetbrans-gateway): update JetBrains IDEs"

---

jfrog-token/README.md
jfrog-token/main.tf

1. Add the [`check_license`](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs#check_license) attribute to skip the pre-flight license check.
2. Add the [`expires_in`](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/scoped_token#expires_in) attribute to control the `expiry time of scoped_tokens used in the workspace.
3. Make the [`refreshable`](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/scoped_token#refreshable) attribute an input to control if the tokens are refreshable.
4. Change the `username_filed` default value to `username` instead of `email`. This will now map the [`data.coder_workspace.me.owner`](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/workspace#owner) to …

fix(jfrog-token)!: add attributes to fine control the token behaviour

---

vscode-desktop/main.tf

Without this the plugin will only work if the user has happened to log in before and that URL was previously saved (and it is the right URL for whatever workspace they are trying to connect).  Otherwise, they get an error about localhost (or if the URL is for a different deployment they would get some other issues).
Fixes https://github.com/coder/coder/issues/10896.

Add missing URL to VS Code desktop module

---

jetbrains-gateway/README.md
jetbrains-gateway/main.test.ts
jetbrains-gateway/main.tf

Another try at #96. I cannot reproduce the error on deployment and dev.coder.com.
It also removes Community editions, `Rider`, and `DataGrip` as they are not supported for Remote Development.

chore(jetbrans-gateway): update JetBrains IDEs and remove community editions

---

code-server/run.sh

Fixes #118
> Not all settings will work with Machine. For example update.mode seems to only be valid for User settings and placing it in Machine will have no effect. So a scope option will probably be necessary (or it will need to default to User).
Changing default to `User`

fix(code-server): write settings to User

---

git-clone/main.tf

also removes the .git from the basename if the user includes it
closes https://github.com/coder/modules/issues/120

feat: enable basename of url to be added to custom path (git-clone)

---

git-clone/README.md
git-clone/main.tf

After #124, we now automatically append the `path` with the `repo` name, so the example should be changed to pass only the base directory as the `path` input.

feat!(git-clone): change `path` input to `base_dir` and return `repo_dir` as output

---

.sample/README.md
CONTRIBUTING.md
README.md
aws-region/README.md
azure-region/README.md
code-server/README.md
coder-login/README.md
dotfiles/README.md
exoscale-instance-type/README.md
exoscale-zone/README.md
filebrowser/README.md
fly-region/README.md
gcp-region/README.md
git-clone/README.md
git-commit-signing/README.md
git-config/README.md
jetbrains-gateway/README.md
jfrog-oauth/README.md
jfrog-token/README.md
jupyter-notebook/README.md
jupyterlab/README.md
package.json
personalize/README.md
slackme/README.md
vault-github/README.md
vscode-desktop/README.md
vscode-web/README.md

This PR enables Terraform formatting in markdown files (via `bun fmt`). Since the `prettier-plugin-terraform-formatter` plugin doesn't register `hcl` we also rename all code-blocks to `tf`, atlernatively we could patch the plugin but I think this is fine.
- chore: add prettier terraform formatting in markdown files
- rename `hcl` codeblocks to `tf` to enable formatter
- bun fmt
- fix invalid tf
- bun fmt

chore: add prettier terraform formatting in markdown files

---

.github/workflows/ci.yaml
CONTRIBUTING.md
exoscale-instance-type/README.md
filebrowser/main.test.ts
filebrowser/run.sh
jfrog-oauth/README.md
new.sh

ci: check for typos

---

lint.ts

This PR lints that there is at least one `tf` block and no `hcl` blocks in the READMEs.
Ref: https://github.com/coder/modules/pull/134#issuecomment-1913148604

chore: lint for tf/hcl blocks

---

vscode-web/main.tf

This PR allows to customize the display name and slug of the VS Code Web module

Allow custom display name and slug for VS Code Web

---

git-commit-signing/run.sh

Closes #149.
in Linux it's fine to modify a file's permissions that only has read permissions if you're the owner, but you still can't write to them, so if the home folder of the user is persisted, then it'll cause issues on every startup, this PR makes the files writable by the owner.
`~/.ssh/git-commit-signing/coder` goes from `400` to `600`
`~/.ssh/git-commit-signing/coder.pub` goes from `400` to `644`
these are the default values when using `ssh-keygen`, I don't know why I didn't use those permissions when writing the script.

fix(git-commit-signing): fix SSH key permissions

---

vault-github/run.sh
vault-token/run.sh

Fixes where the install script was fetching the RC version

fix: fix fetching rc versions of vault cli

---

code-server/main.tf

This PR:
- Adds a `slug` var to the code-server module
- Align the url structure of the vscode-web module with the code-server module

Add slug to code server

---

.github/workflows/update-readme.yaml

This fixes the permission where GA action is unable to submit a PR. See [failed](https://github.com/coder/modules/actions/runs/7947069312/job/21695479135) run for details.
I would appreciate a quick approval.

ci: fix ci permissions

---

hcp-vault-secrets/README.md
hcp-vault-secrets/main.tf

adds `projects_id` as an input.

feat(hcp-vault-secrets): add `project_id` variable to HCP provider

---

.sample/main.tf
code-server/main.tf
filebrowser/main.tf
jetbrains-gateway/main.tf
jupyter-notebook/main.tf
jupyterlab/main.tf
vscode-desktop/main.test.ts
vscode-desktop/main.tf
vscode-web/main.tf

Add per the coder docs coder applications can be reordered in the ui via the order field
https://coder.com/docs/v2/latest/templates/resource-ordering#applications
This change allows this:
```hcl
module "code-server" {
source          = "registry.coder.com/modules/code-server/coder"
version         = "1.0.5"
agent_id        = coder_agent.main.id
install_version = "4.8.3"
order           = 2
}
module "filebrowser" {
source   = "registry.coder.com/modules/filebrowser/coder"
version  = "1.0.3"
agent_id = coder_agent.example.id
folder   = "/home/coder/project"
order    = 1
}
```
See issue #178

feat: add `order` variable to `coder_app` modules

---

code-server/README.md

Doc mention offline suport 
```terraform
module "code-server" {
source         = "registry.coder.com/modules/code-server/coder"
version        = "1.0.7"
agent_id       = coder_agent.main.id
folder         = "/workspace/${local.folder_name}"
install_prefix = "/workspace/.coder-server"
offline = true
settings = {
"workbench.colorTheme" : "Visual Studio Dark"
"workbench.startupEditor" : "readme"
}
extensions = [
"ms-python.python",
"hashicorp.terraform",
"ms-azuretools.vscode-docker"
]
}
```
However there is no filed for this
```
Error: Unsupported argument
on main.tf line 219, in module "code-server":
219:   offline = true
An argument named "offline" is not expected here.
```
closes #181

doc(coder-server): code-server module does not have offline attribute

---

jetbrains-gateway/README.md
jetbrains-gateway/main.tf

Add Jetbrains Rider as a supported IDE
NOTE: This will download `https://download.jetbrains.com/rider/JetBrains.Rider-2023.3.2.tar.gz`, which is not the latest.
closes #187

feat(jetbrains-gateway): add rider support

---

git-commit-signing/run.sh

The module currently logs some output to stderr when there's no error, this PR fixes that.
I tested it and it works
```tf
module "git-commit-signing" {
source   = "git::https://github.com/phorcys420/coder-modules.git//git-commit-signing?ref=git-commit-signing-fix"
agent_id = coder_agent.dev.id
}
```

fix(git-commit-signing): disable curl stderr output

---

jetbrains-gateway/main.tf

Upgrade to the latest:
- IntelliJ IDEA Ultimate (2023.3.5) - https://download.jetbrains.com/idea/ideaIU-2023.3.5.tar.gz
- PhpStorm (2023.3.5) - https://download.jetbrains.com/webide/PhpStorm-2023.3.5.tar.gz
- WebStrom (2023.3.4) - https://download.jetbrains.com/webstorm/WebStorm-2023.3.4.tar.gz
- PyCharm Professional Edition (2023.3.4) - https://download.jetbrains.com/python/pycharm-professional-2023.3.4.tar.gz
- CLion (2023.3.4) - https://download.jetbrains.com/cpp/CLion-2023.3.4.tar.gz
- GoLand (2023.3.5) - https://download.jetbrains.com/go/goland-2023.3.5.tar.gz
- RubyMine (2023.3.5) https://download.jetbrains.com/ruby/RubyMine-2023.3.5.tar.gz
- Rider (2023.3.4) - https://download.jetbrains.com/rider/JetBrains.Rider-2023.3.4.tar.gz

feat(jetbrains-gateway): update ide versions to `2023.3.*`

---

aws-region/main.tf

Add missing regions
- `af-south-1 `    - Africa (Cape Town)
- `ap-east-1`      - Asia Pacific (Hong Kong)
- `ap-south-2`     - Asia Pacific (Hyderabad)
- `ap-southeast-3` - Asia Pacific (Jakarta)
- `ap-southeast-4` - Asia Pacific (Melbourne)
- `ca-west-1`      - Canada West (Calgary)
- `eu-central-2`   - Europe (Zurich)
- `eu-south-1`     - Europe (Milan)
- `eu-south-2`     - Europe (Spain)
- `il-central-1`   - Israel (Tel Aviv)
- `me-south-1`     - Middle East (Bahrain)

feat(aws-region): add missing regions

---

jfrog-token/README.md
jfrog-token/main.tf

This defaults to `"coder-workspace-${lower(data.coder_workspace.me.owner)}-${lower(data.coder_workspace.me.name)}"`  which will render as `coder-workspace-USER_NAME-WORKSPACE_NAME` with the option to overwrite it.

chore(jfrog-token): set token description

---

vscode-web/README.md
vscode-web/main.tf
vscode-web/run.sh

Add support for settings, like code-server
```tf
module "vscode-web" {
source     = "registry.coder.com/modules/vscode-web/coder"
version    = "1.0.8"
agent_id   = coder_agent.example.id
extensions = ["dracula-theme.theme-dracula"]
settings = {
"workbench.colorTheme" = "Dracula"
}
accept_license = true
}
```
Currently saves to `~/.vscode-server/data/Machine/settings.json` as `~/.vscode-server/data/User/settings.json` does not seem to work.
related to #194
closes #196

feat(vscode-web): add support for settings

---

nodejs/main.tf
nodejs/run.sh

Something I did not notice during my testing was, that the directory for `nvm` needs to be created first before the script can be installed. This PR fixes this.

Fix `nodejs`: Create directory before executing script

---

git-commit-signing/main.tf

Change to use the Coder icon for git.svg so we don't need to fetch it externally
@phorcys420 we might want to use the include git.svg hosted by coder.

chore(git-commit-signing): use included icon for git

---

vscode-web/run.sh

MS code-server defaults to using `--host localhost`, which worked perfectly with Coder.
But recently Coder is failing to proxy vscode-web with the https://github.com/coder/coder/issues/12790 
As a workaround, setting `--host 127.0.0.1` works.
ok so Running (the default if we skip `--host`)
`/tmp/vscode-web/bin/code-server serve-local --port 13340 --host localhost --accept-server-license-terms serve-local --without-connection-token --telemetry-level error` gives
```console
Server bound to ::1:13338(IPv6)
Extension host agent listening on 13338
```
But if we set `--host 127.0.0.1`
```console
Server bound to 127.0.0.1:13338 (IPv4)
Extension host agent listening on 13338
[12:55:24] 
Web UI available at http://localhost:13338/
[12:55:24] Extension host agent started.
```
This binds to ipv4.
Is …

fix(vscode-web): set `--host 127.0.0.1`

---

git-config/main.test.ts
git-config/main.tf
test.ts

feat(git-config): allow `data.coder_workspace.me.owner_email` to be blank

---

aws-region/main.test.ts
aws-region/main.tf
azure-region/main.test.ts
azure-region/main.tf
dotfiles/main.test.ts
dotfiles/main.tf
exoscale-instance-type/main.test.ts
exoscale-instance-type/main.tf
exoscale-zone/main.test.ts
exoscale-zone/main.tf
gcp-region/main.test.ts
gcp-region/main.tf
git-config/main.test.ts
git-config/main.tf

Add `coder_parameter_order` variable to modules that have a data coder_parameter
> NOTE: add `coder_parameter_order` for `git-config` could be increments by one, `gcp-region` order should be higher to start with. So intervals by 10 is always safe
```tf
module "git-config" {
source                = "registry.coder.com/modules/git-config/coder"
version               = "1.0.11"
agent_id              = coder_agent.example.id
allow_email_change    = true
coder_parameter_order = 10
}
module "gcp-region" {
source                = "registry.coder.com/modules/gcp-region/coder"
version               = "1.0.11"
regions               = ["us", "europe"]
coder_parameter_order = 20
}
// etc..
```
related to #207

feat: add coder_parameter_order to all data.coder_parameter fields

---

jetbrains-gateway/main.tf

This pull request adds the ability to fetch the JetBrains IDE's latest version dynamically. It adds a new variable to fetch the latest version. The `data.http.jetbrains_ide_versions` data source retrieves the latest version information.
TODO: Add tests (probably in a separate PR)
Closes #217

feat(jetbrains-gateway): Allow fetching latest version dynamically

---

jetbrains-gateway/README.md

add examples on how to use the latest version

docs(jetbrains-gateway): add examples on how to use the latest version

---

apache-airflow/README.md
package-lock.json
package.json

Original readme was pointing to the wrong path, updated it in the code blocks

corrected path in README.md to point to modules/apache-airflow

---

apache-airflow/README.md

getting 500 error when template tries to pull module.  t

changed maintainer_github to coder, added partner_github: nataindata

---

vscode-web/main.test.ts
vscode-web/main.tf
vscode-web/run.sh

feat(vscode-web): add offline, use_cached, extensions_dir and auto_install_extensions

---

dotfiles/main.tf

Fix the title so that "(optional)" is not there twice.
cc: @matifali

fix(dotfiles): remove extra "(optional)" in coder parameter display name

---

git-config/main.test.ts
git-config/main.tf

When upgrading coder/coder TF module to `>= 0.22` the tests will fail
```tf
required_providers {
coder = {
source  = "coder/coder"
version = ">= 0.22"
}
}
```

fix(git-config): add support for coder 0.22

---

coder-login/main.tf
git-config/main.test.ts
git-config/main.tf
github-upload-public-key/main.tf
jfrog-oauth/main.tf
jfrog-token/README.md
jfrog-token/main.tf
vscode-desktop/main.test.ts
vscode-desktop/main.tf

Updates the following modules to no longer reference fields matching coder_workspace.owner_*:
- coder-login
- git-config
- github-upload-public-key
- jfrog-oauth
- vscode-desktop
Also updates dependency of coder/coder to 0.23.0 for the above.
For context, see https://github.com/coder/terraform-provider-coder/releases/tag/v0.23.0
Also closes #255

chore: remove usage of deprecated fields coder_workspace.owner_*

---

code-server/main.tf
code-server/run.sh

To aid faster restarts of workspace with extensions already cached, this change will skip if an extension was already installed.
Before change, extensions would be try to be installed, but this operation can be slow, also extensions are not upgraded
After change with `use_cached_extensions` set, extensions that are already installed are skipped
```tf
module "code-server" {
source                  = "registry.coder.com/modules/code-server/coder"
version                 = "1.0.15"
agent_id                = coder_agent.main.id
order                   = 1
folder                  = "/home/${local.username}/modules"
install_prefix          = "/home/${local.username}/.code-server"
use_cached              = true
auto_install_extensions = true
extensions              = [ …
```

feat(code-server): skip extension if installed

---

windows-rdp/main.tf

Addendum to #262
Accidentally missed one of the URLs before merging the main module.

fix: update SVG icon URL for RDP module

---

code-server/main.tf

When [disable-path-apps](https://coder.com/docs/cli/server#--disable-path-apps) is set on the Coder instance, being able to enable subdomain for the `code-server` module becomes required.
This change is backward compatible.

fix(code-server): add variable for subdomain option

---

windows-rdp/README.md

Tested the corrected URL on dogfood.
Was
```tf
module "windows_rdp" {
source      = "registry.coder.com/coder/module/windows-rdp"
...
}
```
Now
```tf
module "windows_rdp" {
source      = "registry.coder.com/modules/windows-rdp/coder"
...
}
```

fix url schema for webrdp example

---

CONTRIBUTING.md
README.md
lint.ts
slackme/main.test.ts
test.ts
tsconfig.json
vscode-desktop/main.test.ts
windows-rdp/main.test.ts

Little bit of cleanup to make the repo easier to maintain.
- Updated the main contributing guide to include release steps
- Cleaned up TypeScript implementation
- Turned strict mode on
- Removed all `any` types
- Updated all runtime code to account for type changes
- Going to look into adding images or even a gif for the release steps; will look into this on Monday
- I wanted to get the `tsconfig.json` file cleaned up, too (the compiler settings are technically invalid, even though nothing seems to break), but that took me down a rabbi thole of ESM-CSJ interop. Aiming to address that in a separate PR

fix: add missing README information and clean up types

---

code-server/run.sh

Preemptively create specified extension folder in case the parent folder is missing. 
So for example is `/home/local/.ws` was not created yet and the extension path is `/home/local/.ws/extensions` then code server will have the following error.
```bash
Error: ENOENT: no such file or directory, mkdir '/home/local/.ws/extensions'
at Object.mkdirSync (node:fs:1380:26)
at /home/local/.code-server/lib/code-server-4.91.1/lib/vscode/out/vs/server/node/server.main.js:221:1910
at Array.forEach ()
at h (/home/local/.code-server/lib/code-server-4.91.1/lib/vscode/out/vs/server/node/server.main.js:221:1875)
at m (/home/local/.code-server/lib/code-server-4.91.1/lib/vscode/out/vs/server/node/server.main.js:221:2001)
at /home/local/.code-server/lib/code-server-4.91.1/out/node/main.js:42:15
at …
```

fix(code-server): handle when the extension folder does not exist yet

---

git-clone/README.md
git-clone/main.test.ts
git-clone/main.tf

Currently, repositories are always cloned into a folder named after the repo URL.
For example, if you clone `git@github.com:coder/modules.git`, it'll be cloned into a folder called `modules`.
This PR adds a new attribute, `folder_name`. When provided, this name will be used as the destination folder.
In this example, `coder` will be cloned into `~/projects/coder/coder-dev`, where previously it would've been cloned into `~/projects/coder/coder`:
```tf
module "git-clone" {
source      = "registry.coder.com/modules/git-clone/coder"
version     = "1.0.12"
agent_id    = coder_agent.example.id
url         = "https://github.com/coder/coder"
folder_name = "coder-dev"
base_dir    = "~/projects/coder"
}
```

feat(git-clone): custom destination folder name

---

filebrowser/README.md
filebrowser/main.test.ts
filebrowser/main.tf
filebrowser/run.sh

Resolves #285. 
Add variables `workspace_name`, `owner_name` and `resource_name` to be able to infer the directory the module is served at. Set this directory in the filebrowser app via the `filebrowser config set --baseurl` function.
Added an example to readme.

feat(filebrowser): support subdomain = false

---

jupyter-notebook/run.sh
jupyterlab/main.test.ts
jupyterlab/run.sh

Fixes #295 
I have tested both of them on a Ubuntu noble image with pipx.

feat(jupyter): switch from pip3 to pipx for Jupyter install

---

cursor/main.tf

Updates `coder_app`'s display name to Cursor Desktop on @kylecarbs feedback and align with VSCode Desktop.

chore(cursor): update display_name to Cursor Desktop

---

filebrowser/README.md
filebrowser/main.test.ts
filebrowser/main.tf

Ensure that agent_name defaults to an empty string, and introduce
validation to require it when subdomain is true. This aligns with
expected behavior and prevents misconfiguration.

fix(filebrowser): only require agent_name when not on subdomain

---

jetbrains-gateway/README.md
jetbrains-gateway/main.test.ts
jetbrains-gateway/main.tf

Without this, it is not possible to reliably connect to another user's workspace (for admins, mainly) when duplicate workspace names are involved.

Add owner to Gateway link

---

.github/workflows/ci.yaml

CI started failing due to runner images missing the terraform.
I decided to use the same terraform version we use in coder/coder.

chore: explicitly setup terraform

---

vscode-web/README.md
vscode-web/run.sh

fix(vscode-web): remove exit if extension installation fails

---

kasmvnc/run.sh

chore(kasmvnc): refactor download logic to support multiple tools

---

jetbrains-gateway/README.md
jetbrains-gateway/main.tf

- Update with new slug variable to allow using the module multiple times. Resolves #321

feat(jetbrains-gateway): add slug variable

---

filebrowser/README.md
filebrowser/run.sh

fix(filebrowser): support custom base_url in case of custom db path

---

kasmvnc/README.md
kasmvnc/run.sh

I needed to add an `apt-get update` so that it could install dependencies.
I also took the opportunity to cleanup the log output for both `curl` and `apt-get`.
Additionally, we now log the KASM version.
Fixes https://github.com/coder/modules/issues/325

fix(kasmVNC): fix debian installation and improve logging

---

jupyterlab/README.md
jupyterlab/run.sh

Update `command -v` from `jupyterlab` to `jupyter-lab` to check to if jupyterlab binary is installed.

fix(jupyterlab): update command -v from jupyterlab to jupyter-lab

---

jetbrains-gateway/README.md
jetbrains-gateway/main.tf

* Enhance the jetbrains-gateway module to support custom download link.
In [offline mode](https://www.jetbrains.com/help/idea/fully-offline-mode.html), the currently configured offline download address will be overridden by the parameters of jetbrains-gateway(jetbrains-gateway://connect#......&ide_download_link=https://download.jetbrains.com/idea/ideaIU-XXX.tar.gz).

feat(jetbrains-gateway): add releases_base_link/download_base_link variables

---

kasmvnc/README.md
kasmvnc/main.tf
kasmvnc/run.sh

I took the opportunity to majorly refactor the run.sh script.
Basically a rewrite from the ground up, and I found a few things that I don't think were tested for non-Ubuntu distros.
I updated the Kasm Version reference to avoid confusion in the script.
https://github.com/coder/modules/blob/a8cc861e831d796914f965ec5c6c5b1b59aa9118/kasmvnc/main.tf#L42-L46
Removed the extra shebang and added an early exit signal in case of failure.
https://github.com/coder/modules/blob/a8cc861e831d796914f965ec5c6c5b1b59aa9118/kasmvnc/run.sh#L1-L4
Optimize the download function to set the command and then one block of logic to perform the download and handle a failure.
https://github.com/coder/modules/blob/a8cc861e831d796914f965ec5c6c5b1b59aa9118/kasmvnc/run.sh#L16-L37
Created a cross platform function to add …

fix(kasmvnc): optimize KasmVNC deployment script

---

filebrowser/README.md
filebrowser/main.tf
filebrowser/run.sh

Add check if the `filebrowser` exist

feat(filebrowser): check if already installed

---

.github/scripts/check.sh
.github/workflows/check.yaml

Add Instatus API support to monitor module status.

chore: integrate Instatus in check script

---

.github/scripts/check.sh
.github/workflows/check.yaml

- Updated `check.sh` script to add support for automatic re-deploying in the event that the the registry has a partial/full outage.

chore: add updates to force redeployment on Vercel

---

update-version.sh

The script was too greedy and updating unrelated fields in #355.
This change makes the script much more strict, only updating version on the top-level _iff_ within a markdown code-block.

fix(update-versions.sh): handle markdown/tf block nesting when updating version

---

jetbrains-gateway/README.md
jetbrains-gateway/main.test.ts
jetbrains-gateway/main.tf

1. Bumps default IDE versions to 2024.3
2. Set the default value of `latest=true` to always fetch the latest versions.
Extracted from #339 as that introduces a breaking change.

feat(jetbrains-gateway): bump to 2024.3

---

code-server/README.md
code-server/main.tf

```tf
module "code-server" {
source = "git::https://github.com/coder/modules.git//code-server?ref=phorcys/code-server-settings-fix"
settings = {
"workbench.colorTheme" = "Dracula",
"test.test" = ["hi"],
"test.test2" = {
"hello" = "hi"
}
}
agent_id                = coder_agent.dev.id
}
```
Closes #296

fix(code-server): set `settings` variable type to `any`

---

vscode-web/README.md
vscode-web/main.tf

#368 equivalent for vscode-web

fix(vscode-web): set `settings` variable type to `any`

---

git-commit-signing/README.md

Git versions prior to 2.34 do not support commit signing via an SSH key.
I was willing to add a check in the script, but Git does not return the version as-is (sometimes also returns the commit hash) and we would need to compare versions, I think this would add unnecessary dependencies, what do you think @matifali?
```
coder@catfood> git -v
git version 2.47.0
```

chore(git-commit-signing): add version warning in README

---

.github/workflows/ci.yaml
kasmvnc/main.test.ts
setup.ts
test.ts

Closes #389
- Updated our test utilities to reference `process.env` explicitly, and pass it to our child processes
- Made some minor changes to CI and other TypeScript code as minor touch-ups
- This was an issue that actually started on Bun's side. They made a breaking change to their `spawn` function, while also (1) pushing it out in a patch release, and (2) making no mention of the changes in their changelog. I'm not sure if we want to tighten up our Bun versioning going forward, but we can always do that in a later PR

fix: ensure Terraform is available for integration tests

---

dotfiles/README.md
dotfiles/run.sh

If the dotfiles installation (`coder dotfiles ...`) fails, the script still shows as successful in the Coder UI. This should bubble up any errors so that Coder (and the user) are aware that the installation failed.

fix(dotfiles): handle failures in dotfiles installation

---

filebrowser/README.md
filebrowser/main.test.ts
filebrowser/run.sh

On the first start, the DB does not exist and the "filebrowser config set --baseurl" will failed. filebrowser was starting with the wrong baseurl (subdomain=false). it starts correctly on the second try if the db was persisted. this fix set the correct baseurl even if the db was not existing

fix(filebrowser): failed to set server_base_path if db is not existing

---

code-server/README.md
code-server/run.sh
vscode-web/README.md
vscode-web/run.sh

fix: handle extensions.json comments in vscode-web and code-server

---

vscode-web/README.md
vscode-web/main.tf
vscode-web/run.sh

Adds support for specifying a commit ID to pin the vscode-web binary version in the module.

feat(vscode-web): allow pinning vscode-web binary to a specific commit ID

---

vscode-web/README.md
vscode-web/main.tf
vscode-web/run.sh

Adds support for specifying a commit ID to pin the vscode-web version in the module with added example in README.

feat(vscode-web): allow pinning vscode-web version to a specific commit ID

---

jfrog-token/README.md
jfrog-token/main.test.ts
jfrog-token/main.tf

Adds the options to specify a username for the Jfrog user as an input to the module. 
This is useful in cases where Coder usernames and Jfrog usernames are different. 
Ran `bun` tests for the module.

feat(jfrog-token): update module to accept username

---

jupyterlab/README.md
jupyterlab/main.test.ts
jupyterlab/run.sh

Support installation of jupyterlab with UV.

feat(jupyterlab): added support for uv as installer

---

filebrowser/run.sh

Fixes #399 
Instead of trying to cram the config into one command we check if the db exists, if not initialize it then configure the various values before starting the app.

fix(filebrowser): configure before running

---

code-server/README.md
code-server/main.tf

`open_in` option for Coder App was introduced in `2.1.0`. It would be nice to expose it in `code-server` so that we can configure `code-server` to open in new tab instead of new window.

feat(code-server): make `open_in` configurable

---

vault-jwt/README.md
vault-jwt/run.sh

currently, the vault jwt module generates a vault token, but it doesnt actually store it for future vault commands to use.
even with the module configured, running `vault token lookup` fails, because the login command in the module just prints the token but doesnt keep it to be used by future calls to vault
added `-field=token` to the write command, which makes it print only the token itself to stdout, not the rest of the info about the token
then pipe that into `vault login -`, which reads from stdin, and does the process of actually storing the token for future use.
(compared to the other vault coder modules which both call `vault login`, but this one doesnt, but it should.)

fix(vault-jwt): store vault token for use in vault jwt module

---

.github/workflows/deploy-registry.yaml

This pull request updates the GitHub Actions workflow to enhance deployment flexibility by allowing it to trigger on specific tag patterns in addition to pushes to the `main` branch.
Workflow trigger update:
* [`.github/workflows/deploy-registry.yaml`](diffhunk://#diff-fbf55ed2cd70e3380da25686178b863d15e0dcd8b5c8f4115ea33fae51bbd883R7-R8): Added a `tags` condition under the `push` event to trigger the workflow for tags matching the pattern `release/*/v*` (e.g., `release/module-name/v1.0.0`).

ci: deploy dev registry on tag pushes

---

jupyterlab/README.md
jupyterlab/run.sh

If the `jupyter-lab` binary already exists in $PATH, as found by `command -v jupyter-lab`, then we skip installing using `pipx` or `uv`.
By skipping the install path, we leave `${JUPYTERPATH}` unset, which then leads to a broken module unless `jupyter-lab` just so happens to be installed at `/jupyter-lab`.
Fix this by calculating the full path to the binary, either from the install locations of `pipx`, `uv` or, in the case that it was preinstalled, from the preinstalled location.
I did not test this. I would have added a test but the current tests don't run because
they're too slow.

fix(jupyterlab): fix path to jupyter-lab if already installed

---

.github/workflows/deploy-registry.yaml

This PR adds the trigger to auto deploy the prod registry alongside dev when we do a merge to main or tag a release.

ci: add deploy to main trigger

---

jetbrains-gateway/README.md
jetbrains-gateway/main.tf

Provide support for running Jetbrains Gateway connections to both ARM64 and AMD64 hosts.

feat(jetbrains-gateway): add arm64 support
